#
# Copyright 2018 IBM All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2'

volumes:
  orderer.medical.com:
  peer0.providerorg.medical.com:
  peer0.pharmacyorg.medical.com:
  peer0.hospitalorg.medical.com:
  peer0.regulatororg.medical.com:
  peer1.providerorg.medical.com:
  peer1.pharmacyorg.medical.com:
  peer1.hospitalorg.medical.com:
  peer1.regulatororg.medical.com:
networks:
  medical:
services:
  provider-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-providerorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.providerorg.medical.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/PROVIDER_CA_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.providerorg.medical.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/PROVIDER_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/providerorg.medical.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerProviderOrg
    networks:
      - medical

  pharmacy-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-pharmacyorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.pharmacyorg.medical.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/PHARMACY_CA_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.pharmacyorg.medical.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/PHARMACY_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/pharmacyorg.medical.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerPharmacyOrg
    networks:
      - medical

  hospital-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hospitalorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hospitalorg.medical.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/HOSPITAL_CA_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.hospitalorg.medical.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/HOSPITAL_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hospitalorg.medical.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerHospitalOrg
    networks:
      - medical

  regulator-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-regulatororg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.regulatororg.medical.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/REGULATOR_CA_PRIVATE_KEY
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.regulatororg.medical.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/REGULATOR_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/regulatororg.medical.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerRegulatorOrg
    networks:
      - medical

  orderer.medical.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.medical.com
    container_name: orderer.medical.com
    networks:
      - medical

  peer0.providerorg.medical.com:
    container_name: peer0.providerorg.medical.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.providerorg.medical.com
    networks:
      - medical

  peer1.providerorg.medical.com:
    container_name: peer1.providerorg.medical.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.providerorg.medical.com
    networks:
      - medical

  peer0.pharmacyorg.medical.com:
    container_name: peer0.pharmacyorg.medical.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.pharmacyorg.medical.com
    networks:
      - medical

  peer1.pharmacyorg.medical.com:
    container_name: peer1.pharmacyorg.medical.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.pharmacyorg.medical.com
    networks:
      - medical

  peer0.hospitalorg.medical.com:
    container_name: peer0.hospitalorg.medical.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hospitalorg.medical.com
    networks:
      - medical

  peer1.hospitalorg.medical.com:
    container_name: peer1.hospitalorg.medical.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hospitalorg.medical.com
    networks:
      - medical
  peer0.regulatororg.medical.com:
    container_name: peer0.regulatororg.medical.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.regulatororg.medical.com
    networks:
      - medical

  peer1.regulatororg.medical.com:
    container_name: peer1.regulatororg.medical.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.regulatororg.medical.com
    networks:
      - medical
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.providerorg.medical.com:7051
      - CORE_PEER_LOCALMSPID=ProviderOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/providerorg.medical.com/peers/peer0.providerorg.medical.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/providerorg.medical.com/peers/peer0.providerorg.medical.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/providerorg.medical.com/peers/peer0.providerorg.medical.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/providerorg.medical.com/users/Admin@providerorg.medical.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./setupChannel:/opt/gopath/src/github.com/hyperledger/fabric/peer/setupChannel/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./../../fabric-chaincode-evm:/opt/gopath/src/github.com/hyperledger/fabric-chaincode-evm

    depends_on:
      - orderer.medical.com
      - peer0.providerorg.medical.com
      - peer1.providerorg.medical.com
      - peer0.pharmacyorg.medical.com
      - peer1.pharmacyorg.medical.com
      - peer0.hospitalorg.medical.com
      - peer1.hospitalorg.medical.com
      - peer0.regulatororg.medical.com
      - peer1.regulatororg.medical.com
    networks:
      - medical